# Generated by Django 6.0 on 2025-12-24 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.CharField(default='imagengenerica.jpg', max_length=200),
        ),
    ]
