# Generated by Django 6.0 on 2026-01-02 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_categoria_producto_marca_producto_sku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='busqueda_index',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
